//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _05DataFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestTable
    {
        public int Id { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
    }
}
